version: '3'

services:
  mysql:
    container_name: bblili-mysql
    image: mysql:8
    ports:
      - "3306:3306"
    volumes: 
      - /etc/localtime:/etc/localtime
      - ./mysql-init:/docker-entrypoint-initdb.d # 启动脚本
    #  - ./docker/software/mysql/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  Etcd:
    image: bitnami/etcd:latest
    restart: always
    container_name: bblili-etcd
    environment:
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379"
    ports:
      - "2379:2379"
      - "2380:2380"

  redis:
    image:  redis:latest
    restart: always
    container_name: bblili-redis
    command: redis-server --appendonly yes --requirepass '123456'
    environment:
      - TZ=Asia/Shanghai # 设置时区
    ports:
      - 6379:6379


  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    container_name: bblili-elastic
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=test
    restart: always
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.1
    restart: always
    container_name: bblili-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://bblili-elastic:9200
    depends_on:
      - elastic
    ports:
      - 5601:5601

  fastdfs-tracker:
    image: season/fastdfs:1.2
    container_name: bblili-tracker
    restart: no
    ports:
      - 22122:22122
    command: "tracker"

  fastdfs-storage:
    image: season/fastdfs:1.2
    container_name: bblili-storage
    depends_on:
      - fastdfs-tracker
    restart: no
    volumes:
      - "./docker/fastdfs/fdfs_conf/storage.conf:/fdfs_conf/storage.conf"
      - "./docker/fastdfs/store_path:/fastdfs/store_path"
    ports:
      - "23000:23000"
    environment:
      - TRACKER_SERVER=bblili-tracker:22122
    command: "storage"

  fastdfs-nginx:
    image: season/fastdfs:1.2
    container_name: bblili-nginx
    restart: always
    volumes:
      - "./docker/fastdfs/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf"
      - "./docker/fastdfs/store_path:/fastdfs/store_path"
    links:
      - fastdfs-tracker
    ports:
      - "8088:8088"
    environment:
      - TRACKER_SERVER=bblili-tracker:22122
    command: "nginx"

  minio:
    image: minio/minio
    container_name: bblili-minio
    ports:
      - 9000:9000 # api 端口
      - 9001:9001 # 控制台端口
    environment:
      MINIO_ACCESS_KEY: admin    #管理后台用户名
      MINIO_SECRET_KEY: admin123 #管理后台密码，最小8个字符
    command: server --console-address ':9001' /data  #指定容器中的目录 /data
    restart: always