version: '3'

networks:
  bblili_default:
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  mysql:
    container_name: bblili-mysql
    image: mysql:8
    ports:
      - "3306:3306"
    volumes: 
      - /etc/localtime:/etc/localtime
      - ./mysql-init:/docker-entrypoint-initdb.d # 启动脚本
    #  - ./docker/software/mysql/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    networks:
      bblili_default:
        ipv4_address: 172.18.0.2


  Etcd:
    image: bitnami/etcd:latest
    restart: always
    container_name: bblili-etcd
    environment:
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379"
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      bblili_default:
        ipv4_address: 172.18.0.3

  redis:
    image:  redis:latest
    restart: always
    container_name: bblili-redis
    command: redis-server --appendonly yes --requirepass '123456'
    environment:
      - TZ=Asia/Shanghai # 设置时区
    ports:
      - 6379:6379
    networks:
      bblili_default:
        ipv4_address: 172.18.0.4


  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    container_name: bblili-elastic
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=test
    restart: always
    ports:
      - 9200:9200
    networks:
      bblili_default:
        ipv4_address: 172.18.0.5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.1
    restart: always
    container_name: bblili-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://bblili-elastic:9200
    depends_on:
      - elastic
    ports:
      - 5601:5601
    networks:
      bblili_default:
        ipv4_address: 172.18.0.6

  minio:
    image: minio/minio
    container_name: bblili-minio
    ports:
      - 9000:9000 # api 端口
      - 9001:9001 # 控制台端口
    environment:
      MINIO_ACCESS_KEY: admin    #管理后台用户名
      MINIO_SECRET_KEY: admin123 #管理后台密码，最小8个字符
    command: server --console-address ':9001' /data  #指定容器中的目录 /data
    restart: always
    networks:
      bblili_default:
        ipv4_address: 172.18.0.7

  rmqnamesrv:
    container_name: rmqnamesrv
    image: foxiswho/rocketmq:server-4.5.1
    ports:
      - "9876:9876"
    restart: always
    networks:
      bblili_default:
        ipv4_address: 172.18.0.8

  rmqbroker:
    container_name: rmqbroker
    image: foxiswho/rocketmq:broker-4.5.1
    ports:
      - "10911:10911"
      - "10909:10909"
    volumes:
      - ./docker/rocketmq/conf/broker.conf:/etc/rocketmq/broker.conf
    environment:
      NAMESRV_ADDR: "rmqnamesrv:9876"
      JAVA_OPTS: "-Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms512m -Xmx512m"
    command: mqbroker -c /etc/rocketmq/broker.conf
    depends_on:
      - rmqnamesrv
    restart: always
    networks:
      bblili_default:
        ipv4_address: 172.18.0.9

  rmqconsole:
    container_name: rmqconsole
    image: pangliang/rocketmq-console-ng
    environment:
      JAVA_OPTS: "-Drocketmq.config.namesrvAddr=rmqnamesrv:9876 -Drocketmq.config.isVIPChannel=false"
    ports:
      - "8088:8080"
    restart: always
    depends_on:
      - rmqnamesrv
    networks:
      bblili_default:
        ipv4_address: 172.18.0.10