// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"bblili/service/video/internal/logic"
	"bblili/service/video/internal/svc"
	"bblili/service/video/video"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServer) Ping(ctx context.Context, in *video.Request) (*video.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *VideoServer) AddVideo(ctx context.Context, in *video.AddVideoRequest) (*video.AddVideoResponse, error) {
	l := logic.NewAddVideoLogic(ctx, s.svcCtx)
	return l.AddVideo(in)
}

func (s *VideoServer) GetVideos(ctx context.Context, in *video.GetVideosRequest) (*video.GetVideosResponse, error) {
	l := logic.NewGetVideosLogic(ctx, s.svcCtx)
	return l.GetVideos(in)
}

func (s *VideoServer) ViewVideo(ctx context.Context, in *video.ViewVideoRequest) (*video.ViewVideoResponse, error) {
	l := logic.NewViewVideoLogic(ctx, s.svcCtx)
	return l.ViewVideo(in)
}

func (s *VideoServer) GetVideoDetails(ctx context.Context, in *video.GetVideoDetailsRequest) (*video.GetVideoDetailsResponse, error) {
	l := logic.NewGetVideoDetailsLogic(ctx, s.svcCtx)
	return l.GetVideoDetails(in)
}

func (s *VideoServer) Recommend(ctx context.Context, in *video.RecommendRequest) (*video.RecommendResponse, error) {
	l := logic.NewRecommendLogic(ctx, s.svcCtx)
	return l.Recommend(in)
}

func (s *VideoServer) GetVideoSanLian(ctx context.Context, in *video.GetVideoSanLianRequest) (*video.GetVideoSanLianResponse, error) {
	l := logic.NewGetVideoSanLianLogic(ctx, s.svcCtx)
	return l.GetVideoSanLian(in)
}

func (s *VideoServer) GetVideoUserSanLian(ctx context.Context, in *video.GetVideoUserSanLianRequest) (*video.GetVideoUserSanLianResponse, error) {
	l := logic.NewGetVideoUserSanLianLogic(ctx, s.svcCtx)
	return l.GetVideoUserSanLian(in)
}

func (s *VideoServer) OperateVideoSanLian(ctx context.Context, in *video.OperateVideoSanLianRequest) (*video.OperateVideoSanLianResponse, error) {
	l := logic.NewOperateVideoSanLianLogic(ctx, s.svcCtx)
	return l.OperateVideoSanLian(in)
}

func (s *VideoServer) AddVideoComment(ctx context.Context, in *video.AddVideoCommentRequest) (*video.AddVideoCommentResponse, error) {
	l := logic.NewAddVideoCommentLogic(ctx, s.svcCtx)
	return l.AddVideoComment(in)
}

func (s *VideoServer) GetVideoComments(ctx context.Context, in *video.GetVideoCommentsRequest) (*video.GetVideoCommentsResponse, error) {
	l := logic.NewGetVideoCommentsLogic(ctx, s.svcCtx)
	return l.GetVideoComments(in)
}

// 添加弹幕
func (s *VideoServer) AddBarrage(ctx context.Context, in *video.AddBarrageRequset) (*video.AddBarrageResponse, error) {
	l := logic.NewAddBarrageLogic(ctx, s.svcCtx)
	return l.AddBarrage(in)
}

func (s *VideoServer) GetBarrages(ctx context.Context, in *video.GetBarragesRequest) (*video.GetBarragesResponse, error) {
	l := logic.NewGetBarragesLogic(ctx, s.svcCtx)
	return l.GetBarrages(in)
}
