// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	UsernameOrPhoneOrEmail string `json:"usernameOrPhoneOrEmail"`
	Password               string `json:"password"`
}

type LoginResponse struct {
	AuthToken string `json:"authToken"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
}

type UserInfo struct {
	Id     uint64 `json:"id"`
	Nick   string `json:"nick"`
	Avatar string `json:"avatar"`
	Sign   string `json:"sign"`
	Gender int32  `json:"gender"`
	Birth  string `json:"birth"`
}

type UpdateUserInfoRequest struct {
	UserInfo UserInfo `json:"userInfo"`
}

type LogoutRequest struct {
	UserId uint64 `json:"userId"`
}

type GetUserInfoRequest struct {
	UserId uint64 `json:"userId"`
}

type GetUserInfoResponse struct {
	UserInfo UserInfo `json:"userInfo"`
}

type GetUserRequest struct {
	UserId uint64 `json:"userId"`
}

type GetUserResponse struct {
	Username string `json:"username"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
}
