// Code generated by goctl. DO NOT EDIT.
// Source: search.proto

package server

import (
	"context"

	"bblili/service/search/internal/logic"
	"bblili/service/search/internal/svc"
	"bblili/service/search/search"
)

type SearchServer struct {
	svcCtx *svc.ServiceContext
	search.UnimplementedSearchServer
}

func NewSearchServer(svcCtx *svc.ServiceContext) *SearchServer {
	return &SearchServer{
		svcCtx: svcCtx,
	}
}

func (s *SearchServer) Ping(ctx context.Context, in *search.Request) (*search.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *SearchServer) AddUserInfo(ctx context.Context, in *search.AddUserInfoRequest) (*search.AddUserInfoResponse, error) {
	l := logic.NewAddUserInfoLogic(ctx, s.svcCtx)
	return l.AddUserInfo(in)
}

func (s *SearchServer) AddVideo(ctx context.Context, in *search.AddVideoRequest) (*search.AddVideoResponse, error) {
	l := logic.NewAddVideoLogic(ctx, s.svcCtx)
	return l.AddVideo(in)
}

func (s *SearchServer) GetContent(ctx context.Context, in *search.GetContentRequest) (*search.GetContentResponse, error) {
	l := logic.NewGetContentLogic(ctx, s.svcCtx)
	return l.GetContent(in)
}
